# -*- coding: utf-8 -*-
"""student_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM-sJ0fzbVvZkEz5PlxYalNp-sgTgMvI

**Introduction: Student Management System**

Overview: The Student Management System is a menu-driven application created to maintain, retrieve, update and remove student records efficiently. This application allows users to perform multiple operations on the student data such as adding students, searching students, updating student information, generating reports and sorting student data. Student records are stored persistently in a CSV file, allowing information to be retained between program executions. I built this program to strengthen my python programming skills while learning to design reusable software using modular functions, input validation, and clean code architecture

Features: add, view, search, update, remove, reports, CSV persistence

## Features

* Add new student records.
* View all student records.
* Search for students using partial or full names.
* Update existing student information.
* Remove student records.
* Find the oldest and youngest student.
* Calculate the average age of all students.
* Count students above or below a specified age.
* Generate a summary report of student records.
* Display student records sorted by age.
* Store student records persistently using CSV files.

**1. Setup**
"""

from pathlib import Path
from google.colab import drive
import shutil

drive.mount("/content/drive")

DATA_FOLDER = Path(
    "/content/drive/MyDrive/python-student-management-system"
)
DATA_FOLDER.mkdir(parents=True, exist_ok=True)

OLD_FILE = Path("/content/drive/MyDrive/students.csv")
FILE_PATH = DATA_FOLDER / "students.csv"

# Copy the existing CSV only if the new project file does not exist yet
if not FILE_PATH.exists() and OLD_FILE.exists():
    shutil.copy(OLD_FILE, FILE_PATH)
    print("Existing student data moved to the project folder.")

print("Using file:", FILE_PATH)

"""**2. File Handling**

The list exists in RAM. When the program stops --> memory clears --> list disappears
"""

def load_students():
    students = []

    try:
        with open(FILE_PATH, "r") as file:
            header = file.readline()  # Skip the CSV header

            for line in file:
                parts = line.split(",")

                name = parts[0]
                age = int(parts[1].strip())

                student = {"Name": name, "Age": age}
                students.append(student)

    except FileNotFoundError:
        return []

    return students

def save_students(students):
  with open(FILE_PATH, "w") as file:
    file.write("Name,Age\n")

    for item in students:
      file.write(f"{item['Name']},{item['Age']}\n")

"""**3. Load Active Data**"""

students = load_students() #Very IMPORTANT ---> rebuild active application memory
#load_students() it is either a saved CSV file which is later converted to dictionary or there exists no CSV file and we use empty dictionary

"""**4. Basic Validators**"""

def valid_name(name):
  if name.strip() == "":
    print("Name cannot be empty")
    return False

  for char in name:
    if not char.isalpha() and not char.isspace():
      print("Invalid Name. Please use letters and spaces only.")
      return False

  return True

def valid_age(age):

  if not age.isdigit():
    return False
  return True

def valid_choice(choice, max_choice):

  if not choice.isdigit():
    return False

  choice = int(choice)

  if choice < 1 or choice > max_choice:
    return False
  return True

def is_empty(students):
  if not students:
    print("List is empty")
    return True
  return False

"""**6. Search/helper utilities**"""

#Separation of Concern: find_matching_students

def find_matching_students(students, query): #helper function
  matching_students = []

  query = query.lower()

  for item in students:
    #A search should match whole words, not random letter sequences inside words.
    if query in item["Name"].lower().split():
      matching_students.append(item)
  return matching_students

def get_age(student):
  return student["Age"]

#sorted_students = sorted(students,key = get_age)
#print(sorted_students)

"""**7. Core Actions**



*   add_student()
*   view_students()


*   search_student()
*   update_student()


*   remove_student()






"""

def save_students(students):
    with open(FILE_PATH, "w") as file:
        file.write("Name,Age\n")

        for student in students:
            file.write(f"{student['Name']},{student['Age']}\n")

def add_student(students):
  while True: #outer loop
    Name = input("Enter name of student or ! to stop: ").strip()

    if Name == "!":
      print("Adding students stopped.")
      break

    if not valid_name(Name):  #if the name is not valid continue the loop --> take new input. if not True then continue if not False do not continue
      continue

    while True: #inner loop
      Age = input("Enter age of student: ")

      if not valid_age(Age):
        continue

      Age = int(Age)
      break

    student = {"Name": Name, "Age": Age}
    students.append(student)
    save_students(students)
    print("Student added successfully.")

# def is_empty(students):
#   if not students:
#     print("List is empty")
#     return True #returns true when empty
#   else:
#     return False #returns false when not empty

def view_students(students):
  if is_empty(students):
    return

  for item in students:
    print(f"Name: {item['Name']}, Age: {item['Age']}")

#Upgraded version of search_student

def search_student(students): #main function
  if is_empty(students):
    return

  input_name = input("Enter Student's Name: ")

  matching_students = find_matching_students(students, input_name)

  if not matching_students:
    print("Student not found.")
    return

  print("Matching students:")

  for item in matching_students:
    print(f"Student Details - Name: {item['Name']}, Age: {item['Age']}")

#New update_student function

def update_student(students):
  if is_empty(students):
    return

  input_name = input("Enter name to update: ")

  matching_students = find_matching_students(students, input_name)

  if not matching_students:
    print("Student not found.")
    return

  count = 1

  for item in matching_students:
    print(f"{count}. Name: {item['Name']}, Age: {item['Age']}")
    count += 1

  choice = input("Choose student to update: ")

  if not valid_choice(choice, len(matching_students)): #using the valid_choice helper function
    print("Invalid Choice.")
    return

  choice = int(choice)

  index = choice - 1
  selected_student = matching_students[index]

  print("What do you want to update?")
  print("1. Name")
  print("2. Age")
  print("3. Both")

  field_choice = input("Enter choice: ")

  if not valid_choice(field_choice, 3): #using helper function here
    print("Invalid choice.")
    return

  field_choice = int(field_choice)

  if field_choice == 1:
    updated_name = input("Enter Name of Student.")

    if not valid_name(updated_name):
      print("Invalid Name.")
      return
    else:
      selected_student["Name"] = updated_name
      print("Name Successfully Updated.")

  elif field_choice == 2:
    updated_age = input("Enter Age of Student.")

    if not valid_age(updated_age):
      print("Invalid Age")
      return
    else:
      selected_student["Age"] = int(updated_age)
      print("Age Successfully Updated.")

  elif field_choice == 3:
    updated_name = input("Enter Name of Student.")
    updated_age = input("Enter Age of Student.")

    if not valid_name(updated_name):
      print("Invalid Name.")
      return
    else:
      selected_student["Name"] = updated_name
      print("Name Successfully Updated.")

    if not valid_age(updated_age):
      print("Invalid Age")
      return
    else:
      selected_student["Age"] = int(updated_age)
      print("Age Successfully Updated.")

  else:
    print("Invalid choice.")
    return

#choice = int(choice)
#you are only rebinding the local choice inside that function.
#The outside variable remains unchanged.

#New Remove Function: Implementing Separation of Concern

def remove_student(students):
  if is_empty(students):
    return

  input_name = input("Enter Student's Name: ")

  matching_students = find_matching_students(students, input_name)

  if not matching_students:
    print("student not found")
    return

  count = 1

  for item in matching_students:
    print(f"{count}. Name: {item['Name']}, Age: {item['Age']}") # writing the students in matching_students with serial
    count += 1

  choice = input("Enter student number to remove: ")

  if not valid_choice(choice, len(matching_students)): #using the valid_choice helper function
    print("Invalid Choice.")
    return

  choice = int(choice)

  index = choice -1 #index starts at 0 and choice starts at 1, hence we subtract 1 to get teh index value

  student_to_remove = matching_students[index]
  students.remove(student_to_remove)

  print("Student removed successfully.")

"""**# 8. Analytics/reporting**



---



*   average_age()



*  count_students_above_age()
*  count_students_below_age()






*   youngest_student()
*   oldest_student()



*   find_topper()
*   student_report()


*   view_students_sorted()








"""

def average_age(students):

  if not students:
        return None

  total_age = 0

  for item in students:
    total_age += item["Age"]

  average = total_age/len(students)
  return average

def count_students_above_age(students, threshold):

  if not students:
    return 0

  count = 0

  for item in students:
    if item["Age"] > threshold:
      count += 1

  return count

def count_students_below_age(students,threshold):

  if is_empty(students):
    #print("List is empty.")
    return 0

  count = 0

  for item in students:
    if item["Age"] < threshold:
      count += 1
  return count

def youngest_student(students):

  if is_empty(students):
    return None

  youngest = students[0]

  for item in students[1:]:
    if item["Age"]< youngest["Age"]:
      youngest = item

  #print(f"Youngest: {youngest['Name']}, Age: {youngest['Age']}")
  return youngest

def oldest_student(students):

  if is_empty(students):
    return None

  oldest = students[0]

  for item in students[1:]:
    if item["Age"]>oldest["Age"]:
      oldest = item

  return oldest

def find_Oldest_student(students):
  #To handle Empty list
  if is_empty(students):
    return

  topper = students[0] #students is a list ----> we store the first dictionary entry here in variable topper

  for item in students: #so we look for an entry in the list specifically in key age
    if topper["Age"] < item["Age"]: #if the age entry stored in the entire list is greater than the  topper variable one, we store that new maximum one in topper
      topper = item

  #return(topper) #returning the dictionary entry with highest age
  print(f"Topper: {topper['Name']}, Age: {topper['Age']}")

def student_report(students):

  if is_empty(students):
    return None

  print("----- Student Summary Report -----")
  print("Total students:", len(students))
  print("Average age:", average_age(students))

  youngest = youngest_student(students)
  print(f"Youngest: {youngest['Name']}, Age: {youngest['Age']}")

  oldest = oldest_student(students)
  print(f"Oldest: {oldest['Name']}, Age: {oldest['Age']}")

def view_students_sorted(students):
  if is_empty(students):
    return None

  sorted_students = sorted(students, key = get_age)
  #sorted function compated the dictionaries using age and returned reordered dictionaries

  for student in sorted_students:
    name = student["Name"]
    age = student["Age"]
    #print(f"Name : {student['Name']}, Age : {student['Age']}")
    print(f"Name: {name}, Age: {age}")

"""**# 9. Menu dictionary**

**Clean up the menu save logic so only add/update/remove trigger save_students(students)**
"""

menu = {1: {"function" : add_student, "type" : "print", "changes_data": True},
        2: {"function" : view_students, "type" : "print", "changes_data": False},
        3: {"function" : find_Oldest_student, "type" : "print", "changes_data": False},
        4: {"function" : update_student, "type": "print", "changes_data": True},
        5: {"function" : remove_student, "type": "print", "changes_data": True},
        6: {"function" : search_student, "type" : "print", "changes_data": False},
        7: {"function" : youngest_student, "type": "return"},
        8: {"function" : average_age, "type": "return"},
        9: {"function" : count_students_above_age, "type": "input", "inputs" : {"threshold" : int}},
        11: {"function" : count_students_below_age, "type": "input", "inputs" : {"threshold": int}},
        12: {"function" : student_report, "type": "print", "changes_data": False},
        13: {"function": view_students_sorted, "type": "print", "changes_data" : False}}

def run_menu(students):
    while True:

        print("""Choose an option:
1. Add Student
2. View Students
3. Find Oldest Student
4. Update Student
5. Remove Student
6. Search Student
7. Youngest Student
8. Average age
9. Counts students over a threshold
10. Exit Program
11. Counts students below a threshold
12. Student Summary Report
13. View sorted student report""")

        choice = input("Enter your choice: ")

        if not choice.isdigit():
            print("Invalid Input")
            continue

        choice = int(choice)

        if choice == 10:
            print("Program Exited.")
            break

        if choice not in menu:
            print("Invalid choice.")
            continue

        # Get menu details
        entry = menu[choice]
        function = entry["function"]
        func_type = entry["type"]

        if func_type == "print":
            function(students)

            if entry["changes_data"]:
                save_students(students)

        elif func_type == "return":
            result = function(students)

            if result is None:
                print("No students available.")
            else:
                print(result)

        elif func_type == "input":
            inputs = entry["inputs"]
            input_values = {}

            for input_name, input_type in inputs.items():
                # Example:
                # input_name = "threshold"
                # input_type = int

                user_value = input(f"Enter {input_name}: ")

                try:
                    converted_value = input_type(user_value)

                except ValueError:
                    print(f"Invalid {input_name}.")
                    break

                input_values[input_name] = converted_value

            else:
                result = function(students, *input_values.values())
                print(result)

"""**# 10. Menu runner**"""

def main():
    students = load_students() #students is the list
    run_menu(students)

if __name__ == "main": #This means: “only run the app when this file is executed directly.”
#a safety gate for running programs in bigger Python projects.
    main()

run_menu(students)

"""Composition: small reusable functions -> combined into larger functionality"""

student_report(students)

print("Current file:", FILE_PATH)

with open(FILE_PATH, "r") as file:
    print(file.read())